apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-lrci
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eqkp-tenant/rhtap-demo-app/hacbs-test-project-lrci@sha256:d76f12fbabe417acc8f16b26e34b8b407d490805ad6dcf67d0b1a620d00073b2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
