apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-lrci
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eqkp-tenant/rhtap-demo-app/hacbs-test-project-lrci@sha256:96d4031c525ead620d87cd570754c83d091aaafec7f7dcad34c94c944cd5d72a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
