apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lrci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lrci
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-lrci
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lrci
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lrci
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eqkp-tenant/rhtap-demo-app/hacbs-test-project-lrci@sha256:96d4031c525ead620d87cd570754c83d091aaafec7f7dcad34c94c944cd5d72a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
